version: 2.1

# Define resource classes
resource_class:
  small: &small
    cpu: 2
    memory: 4GB
  medium: &medium
    cpu: 4
    memory: 8GB
  large: &large
    cpu: 8
    memory: 16GB

jobs:
  # Define job templates
  lint:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
      - run: golangci-lint run ./...
  test:
    parallelism: 2
    docker:
      - image: circleci/golang:1.17
      <<: *medium
    steps:
      - checkout
      - run: go mod download
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
    # Cache dependencies between runs
    key: go-modules-{{ .Branch }}-{{ checksum "go.mod" }}
    caches:
      - path: ~/go/pkg/mod

  build:
    docker:
      - image: golang:1.17
      <<: *large
    steps:
      - checkout
      - run: go mod download
      - run: go build -o pulse-server .
    # Cache dependencies between runs
    key: go-modules-{{ .Branch }}-{{ checksum "go.mod" }}
    caches:
      - path: ~/go/pkg/mod

  deploy:
    docker:
      - image: alpine
      <<: *small
    steps:
      - checkout
      - run: echo "Deploying..."

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - lint
      - test:
          requires:
            - lint
          filters:
            branches:
              only: master
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master