version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/gopulse/pulse

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: |
            go mod download

      # Build and test
      - run:
          name: Build and Test
          command: |
            go build -v ./...
            go test -timeout=10m -v ./...

      # Upload coverage report
      - run:
          name: Upload Coverage Report
          command: |
            bash <(curl -s https://codecov.io/bash) -f coverage.out -t $CODECOV_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - build
