name: "Bug Report"
title: "Bug: "
description: Report a bug to help us improve this project.
labels: [":bug: Bug"]

body:
  - type: markdown
    id: recommendations
    attributes:
      value: |
        ### Before you submit
        - Don't forget you can ask your questions in our [Discord server](https://discord.com/invite/JKcTwZYJ).
        - Write your issue clearly.
  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and detailed description of the bug you would like to see fixed."
      placeholder: "Explain your bug clearly, and in detail."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: "How to Reproduce"
      description: "Steps to reproduce the behavior."
      placeholder: "
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error"
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
      placeholder: "Explain what you expected to happen."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Version"
      description: "The version of Pulse you are using."
      placeholder: "v1.0.0"
    validations:
      required: true

  - type: textarea
    id: snippet
    attributes:
      label: "Code Snippet (optional)"
      description: "Code snippet may be really helpful to describe some bugs."
      placeholder: "Share a code snippet to explain the bug better."
      render: go