on:
  push:
    branches: [master]
    paths: ['**']
  pull_request:
    paths: ['**']

jobs:
  coverage_report:
    name: Update coverage report
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: 'true'
          chart: 'true'
          amend: 'false'
