on:
  push:
    branches: [master]
    paths: ['**']
  pull_request:
    paths: ['**']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: go test -v ./...

  coverage_report:
    name: Update coverage report
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage report
        uses: ncruces/go-coverage-report@v0.1.6